p8105_hw2_gj2356
================
Ghislaine Jumonville
2023-09-27

## PROBLEM 1

Cleaning the dataset `pols-month.csv` in the code chunk below. In the
new dataframe `pols_month_df`, the variable `mon` is separated into
`year`, `month`, and `day`. There is a new variable `president` that
takes on the values `dem` if `prez_dem = 1` or `gop` if `prez_gop = 1`.
The variables `prez_dem`, `prez_gop`, and `date` are removed from the
final data frame.

``` r
pols_month_df = read_csv("./fivethirtyeight_datasets/pols-month.csv") |>
                separate(mon, into = c("year", "month", "day"), sep = "-") |> 
                mutate(
                  month = 
                          case_match(
                            month,
                            "01" ~ "Jan",
                            "02" ~ "Feb",
                            "03" ~ "Mar",
                            "04" ~ "Apr",
                            "05" ~ "May",
                            "06" ~ "Jun",
                            "07" ~ "Jul",
                            "08" ~ "Aug",
                            "09" ~ "Sep",
                            "10" ~ "Oct",
                            "11" ~ "Nov",
                            "12" ~ "Dec"),
                  month = as.factor(month)) |> 
                mutate(
                  president = case_when( prez_gop == 1 ~ "gop", 
                                              prez_gop == 0 ~ "dem" )) |> 
              select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Cleaning the next dataset `snp.csv` in the code chunk below. The
resulting data frame `snp_df` has the `date` split into `month`and
`year` with `day` removed. The months have been translated from numbers
to their names. I have added either `20` or `19` to the beginning of the
years so that they have four characters.

``` r
snp_df = read_csv("./fivethirtyeight_datasets/snp.csv") |> 
        separate(date, into = c("month", "day", "year"), sep = "/") |> 
        select(year, month, close) |> 
        mutate(
            month = 
                  case_match(
                    month,
                      "1" ~ "Jan",
                      "2" ~ "Feb",
                      "3" ~ "Mar",
                      "4" ~ "Apr",
                      "5" ~ "May",
                      "6" ~ "Jun",
                      "7" ~ "Jul",
                      "8" ~ "Aug",
                      "9" ~ "Sep",
                      "10" ~ "Oct",
                      "11" ~ "Nov",
                      "12" ~ "Dec"),
            month = as.factor(month)) |> 
        mutate(
          year = 
            case_when(
              year < 16 ~ paste0("20", year),
              year >= 16 ~ paste0("19", year))
            )
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Cleaning the last dataset `unemployment.csv` in the code chunk below.
Here I used `pivot_longer` to transform the existing data frame to have
more rows and less columns by making two new variables `month` and
`percent_unemployment`. I also had to rename `Year` to `year` and make
it a character variable type instead of numeric for joining purposes.

``` r
unemployment_df = read_csv("./fivethirtyeight_datasets/unemployment.csv") |> 
                  pivot_longer(
                      Jan:Dec,
                      names_to = "month",
                      values_to = "percent_unemployment") |> 
                  rename(year = Year) |> 
                  mutate(year = as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Here I used `left_join` to join `snp_df` into `pols_month_df` by `year`
and `month` to create `snp_pols_df`. Then I repeated the process joining
`unemployment_df` into `snp_pols_df` to create the final data frame
`hw2_joined_df`.

``` r
snp_pols_df = left_join(pols_month_df, snp_df, by = c("year","month"))
hw2_joined_df = left_join(snp_pols_df, unemployment_df, by = c("year","month"))
```

The first dataset `pols_month_df` contained 822 observations and 9
variables that had information on US politicians and their political
affiliations at different times, ranging from 1947 to 2015. The next
dataset `snp_df` contained 787 observations and 2 variables that showed
the Standard & Poor’s stock market index (S&P) and the corresponding
date with years ranging from 1950 to 2015. The last dataset
`unemployment_df` contained 68 observations and 13 variables before it
was transformed. There was information about the percentage of
unemployment for each month and year, ranging from 1948 to 2015.

The final and resulting dataset from joining the 3 aforementioned
datasets together, `hw2_joined_df`, has 822 observations and 11
variables. The range of `year` is from 1947 to 2015. There is
information on the political affiliation of the president (`president`)
for any given year along with the number of national politicians that
are either democratic or republican. There is also information on the
S&P at the time (`close`) along with unemployment percentages
(`percent_unemployment`).

## PROBLEM 2

Mr. Trash Wheel

``` r
library(readxl)
mr_trash_df = 
  read_excel("./202207 Trash Wheel Collection Data.xlsx", 
             sheet = "Mr. Trash Wheel", 
             range = "A2:N549", 
             col_names = TRUE) |> 
  janitor::clean_names() |> 
  select(-year) |> 
  separate(date, into = c("year", "month_num", "day"), sep = "-") |> 
  select(dumpster, year, month, day, everything(), -month_num) |> 
  mutate(
    homes_powered = ((weight_tons*500)/30),
    trash_wheel = "Mr"
  )
head(mr_trash_df)
```

    ## # A tibble: 6 × 15
    ##   dumpster year  month day   weight_tons volume_cubic_yards plastic_bottles
    ##      <dbl> <chr> <chr> <chr>       <dbl>              <dbl>           <dbl>
    ## 1        1 2014  May   16           4.31                 18            1450
    ## 2        2 2014  May   16           2.74                 13            1120
    ## 3        3 2014  May   16           3.45                 15            2450
    ## 4        4 2014  May   17           3.1                  15            2380
    ## 5        5 2014  May   17           4.06                 18             980
    ## 6        6 2014  May   20           2.71                 13            1430
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, trash_wheel <chr>

Professor Trash Wheel

``` r
prof_trash_df =
  read_excel("./202207 Trash Wheel Collection Data.xlsx", 
             sheet = "Professor Trash Wheel", 
             range = "A2:M96", 
             col_names = TRUE) |> 
  janitor::clean_names() |> 
  select(-year) |> 
  separate(date, into = c("year", "month_num", "day"), sep = "-") |> 
  select(dumpster, year, month, day, everything(), -month_num) |> 
  mutate(
    homes_powered = ((weight_tons*500)/30),
    trash_wheel = "Professor"
  )
head(prof_trash_df)
```

    ## # A tibble: 6 × 14
    ##   dumpster year  month    day   weight_tons volume_cubic_yards plastic_bottles
    ##      <dbl> <chr> <chr>    <chr>       <dbl>              <dbl>           <dbl>
    ## 1        1 2017  January  02           1.79                 15            1950
    ## 2        2 2017  January  30           1.58                 15            9540
    ## 3        3 2017  February 26           2.32                 18            8350
    ## 4        4 2017  February 26           3.72                 15            8590
    ## 5        5 2017  February 28           1.45                 15            7830
    ## 6        6 2017  March    30           1.71                 15            8210
    ## # ℹ 7 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, trash_wheel <chr>

Gwynnda Trash Wheel

``` r
gwynnda_trash_df =
  read_excel("./202207 Trash Wheel Collection Data.xlsx", 
             sheet = "Gwynnda Trash Wheel", 
             range = "A2:K108", 
             col_names = TRUE) |> 
  janitor::clean_names() |> 
  select(-year) |> 
  separate(date, into = c("year", "month_num", "day"), sep = "-") |> 
  select(dumpster, year, month, day, everything(), -month_num) |> 
  mutate(
    homes_powered = ((weight_tons*500)/30),
    trash_wheel = "Gwynnda"
  )
head(gwynnda_trash_df)
```

    ## # A tibble: 6 × 12
    ##   dumpster year  month  day   weight_tons volume_cubic_yards plastic_bottles
    ##      <dbl> <chr> <chr>  <chr>       <dbl>              <dbl>           <dbl>
    ## 1        1 2021  July   03           0.93                 15            1200
    ## 2        2 2021  July   07           2.26                 15            2000
    ## 3        3 2021  July   07           1.62                 15            1800
    ## 4        4 2021  July   16           1.76                 15            1000
    ## 5        5 2021  July   30           1.53                 15            2100
    ## 6        6 2021  August 11           2.06                 15            2400
    ## # ℹ 5 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   plastic_bags <dbl>, homes_powered <dbl>, trash_wheel <chr>

Join

``` r
trash_tidy =
  bind_rows(mr_trash_df, prof_trash_df, gwynnda_trash_df) |> 
  select(trash_wheel, everything())
```

The total weight of trash collected by Professor Trash was 190.12. The
total number of cigarette butts collected by Gwynnda in July 2021 was
2.65031^{6}.

## PROBLEM 3

The code chunk below imports and cleans the data set `mci_baseline`
which contains basic demographic information measured at the study
baseline. To import the data set, I had to skip the first row because
the first row was additional information and not variable names. The
data set includes variables `id`, `current_age`, `sex`, `education`,
`apoe4`, and `age_at_onset`. To clean the data set, I encoded `sex` as a
character variable with two values: either “male” or “female”. I also re
coded the `apoe4` variable which indicates a participants carrier status
as either “carrier” or “non-carrier”, and changed `age_at_onset` value
“.” to “NA”. The final step included filtering out any participants that
did not meet the study criteria, meaning that they had developed MCI
prior to being enrolled in the study (`age_current` \> `age_at_onset`).

``` r
mci_baseline_df = read_csv("./data_mci/mci_baseline.csv",
                           skip = 1) |> 
                  janitor::clean_names() |>
                  mutate(
                    sex = 
                      case_match(
                        sex,
                        1 ~ "male",
                        0 ~ "female"),
                    apoe4 = 
                      case_match(
                        apoe4,
                        1 ~ "carrier",
                        0 ~ "non-carrier"),
                    age_at_onset = 
                      case_match(
                        age_at_onset,
                        "." ~ "NA",
                        .default = age_at_onset)) |> 
                  filter(current_age < age_at_onset)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

There are 479 participants and 93 develop MCI. The average baseline age
is 65.0286013 and 0.3 of women are APOE4 carriers.

``` r
janitor::tabyl(mci_baseline_df,sex, apoe4) #what proportion of women in the study are APOE4 carriers
```

    ##     sex carrier non-carrier
    ##  female      63         147
    ##    male      81         188

The code chunk below imports and cleans the data set `mci_amyloid`.
Similarly, I had to skip the first row when importing because the first
row was not variable names and just offered extra information. I renamed
`study_id` to `id` so that I can merge the baseline data set with this
one.

``` r
mci_amyloid_df = read_csv("./data_mci/mci_amyloid.csv",
                          skip = 1) |> 
                janitor::clean_names() |> 
                rename(id = study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
