---
title: "p8105_hw2_gj2356"
author: "Ghislaine Jumonville"
date: "2023-09-27"
output: github_document
---

## PROBLEM 1

```{r}
pols_month_df = read.csv("fivethirtyeight_datasets/pols-month.csv") |>
                separate(mon, into = c("year", "month", "day"), sep = "-") |> 
                mutate(
                  month = 
                          case_match(
                            month,
                            "01" ~ "January",
                            "02" ~ "February",
                            "03" ~ "March",
                            "04" ~ "April",
                            "05" ~ "May",
                            "06" ~ "June",
                            "07" ~ "July",
                            "08" ~ "August",
                            "09" ~ "September",
                            "10" ~ "October",
                            "11" ~ "November",
                            "12" ~ "December"),
                  month = as.factor(month) |> 
                mutate(
                  president = case_when( prez_gop == 1 ~ "gop", 
                                              prez_gop == 0 ~ "dem" )
)
```


```{r}
pols_month_df = mutate(pols_month_df, president = case_when( prez_gop == 1 ~ "gop", prez_dem == 1 ~ "dem" ) 
```

